### ISSUE TITLE
bridge crashes on startup (OSX)

### ISSUE THREAD

**Issue by lunokhod** [Storj/bridge#126]
I am trying to get the storj bridge running on OSX, but it crashes with the following output. It is quite possible that I am doing something wrong as this is the first time trying.
~~~~
% npm install
% npm run develop

> storj-bridge@0.9.3 develop /Users/lunokhod/Storj/bridge
> STORJ_ALLOW_LOOPBACK=1 NODE_ENV=devel node script/develop.js

Storj Bridge in DEVELOP mode with configuration:

Config {
  storage: 
   { host: '127.0.0.1',
     port: 27017,
     name: '__storj-bridge-develop' },
  messaging: 
   { url: 'amqp://localhost',
     queues: { renterpool: [Object], callback: [Object] },
     exchanges: { events: [Object] } },
  server: { host: '127.0.0.1', port: 6382, ssl: {} },
  network: { minions: [ [Object], [Object], [Object] ] },
  mailer: 
   { host: '127.0.0.1',
     port: 465,
     secure: true,
     auth: { user: 'username', pass: 'password' },
     from: 'robot@storj.io' } }

{"level":"info","message":"starting messaging","timestamp":"2016-06-28T21:05:00.843Z"}
{"level":"error","message":"Error connecting to amqp://localhost: connect ECONNREFUSED 127.0.0.1:5672","timestamp":"2016-06-28T21:05:00.851Z"}
{"level":"info","message":"you are configured to tunnel up to 3 connections","timestamp":"2016-06-28T21:05:00.882Z"}
{"level":"info","message":"node created with nodeID 0a40589171fd32c6bcc31af894490eb6499d77dc","timestamp":"2016-06-28T21:05:00.889Z"}
/Users/lunokhod/Storj/bridge/node_modules/storj/lib/network/index.js:187
  if (this._options.seeds.length) {
                         ^

TypeError: Cannot read property 'length' of undefined
    at FarmerInterface.Network._enterOverlay (/Users/lunokhod/Storj/bridge/node_modules/storj/lib/network/index.js:187:26)
    at /Users/lunokhod/Storj/bridge/node_modules/storj/lib/network/index.js:155:10
    at FarmerInterface.Network._setupTunnelClient (/Users/lunokhod/Storj/bridge/node_modules/storj/lib/network/index.js:533:12)
    at FarmerInterface.Network.join (/Users/lunokhod/Storj/bridge/node_modules/storj/lib/network/index.js:150:8)
    at FarmerInterface.join (/Users/lunokhod/Storj/bridge/node_modules/storj/lib/interfaces/farmer.js:90:26)
    at FarmerInterface.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at FarmerInterface.emit (events.js:185:7)
    at FarmerInterface.Network._onTransportOpen (/Users/lunokhod/Storj/bridge/node_modules/storj/lib/network/index.js:334:8)
    at /Users/lunokhod/Storj/bridge/node_modules/kad/node_modules/async/lib/async.js:607:21
    at /Users/lunokhod/Storj/bridge/node_modules/kad/node_modules/async/lib/async.js:246:17
    at iterate (/Users/lunokhod/Storj/bridge/node_modules/kad/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/Users/lunokhod/Storj/bridge/node_modules/kad/node_modules/async/lib/async.js:162:9)
    at _asyncMap (/Users/lunokhod/Storj/bridge/node_modules/kad/node_modules/async/lib/async.js:245:13)
    at Object.mapSeries (/Users/lunokhod/Storj/bridge/node_modules/kad/node_modules/async/lib/async.js:228:23)
    at Object.async.series (/Users/lunokhod/Storj/bridge/node_modules/kad/node_modules/async/lib/async.js:605:19)
~~~~

**Comment by bryanchriswhite** [comment]
@lunokhod have you tried `NODE_ENV=develop storj-bridge` instead?

**Comment by lunokhod** [comment]
The syntax `NODE_ENV=develop storj-bridge` doesn't work in most unix shells, but I did set the NODE_ENV variable to develop and retried, with the same result.  I will try vagrant at some point, but that is not a permanent solution.

**Comment by bryanchriswhite** [comment]
@lunokhod i'm not sure what you mean by 
> The syntax NODE_ENV=develop storj-bridge doesn't work in most unix shells
I do that all the time on OSX and linux in zsh or bash and have never had and issue. An alternative would be to:

```
export NODE_ENV=develop
storj-bridge
```
as two seperate commands. But I suspect that the issue isn't how you're starting the server.

LMK if setting up rabbitmq changes anything.

**Comment by lunokhod** [comment]
You were right about rabbitmq. This can be installed via
```
brew install rabbitmq
```
and then started with 
```
rabbitmq-server
```
I'll close this for now, and then update the readme file after I get everything worked out with the gui.
(As for the other question, there should be either a colon `;` or `&&` between the two commands if you enter them on the same line).
