### ISSUE TITLE
Consignment is not authorized

### ISSUE THREAD

**Issue by genavyshel** [Storj/bridge#180]
### Package Versions

```
gitrepo commit d92b01c
```

Replace the values below using the output from `node --version`.

```
v4.4.6
```

### Expected Behavior

```
  The file must be uploaded or message "No storage offers were received" sent back to the client
```

### Actual Behavior

```
  From time to time bridge server return responses with error "Consignment is not authorized"

osboxes@osboxes:~/Documents/gitrepos/core$ node bin/storj.js upload-file 57ab6354a5ce2d240e2632aa ~/Downloads/package.json.downloaded 
 [...]  > Enter your passphrase to unlock your keyring  >  ******

 [Tue Aug 16 2016 11:16:49 GMT+0300 (MSK)] [info]   Generating encryption key...
 [Tue Aug 16 2016 11:16:49 GMT+0300 (MSK)] [info]   Encrypting file "/home/osboxes/Downloads/package.json.downloaded"
 [Tue Aug 16 2016 11:16:49 GMT+0300 (MSK)] [info]   Encryption complete!
 [Tue Aug 16 2016 11:16:49 GMT+0300 (MSK)] [info]   Creating storage token...
 [Tue Aug 16 2016 11:16:50 GMT+0300 (MSK)] [info]   Storing file, hang tight!
 [Tue Aug 16 2016 11:16:50 GMT+0300 (MSK)] [info]   Trying to upload shard /tmp/ec948e0a8eb0 index 0
 [Tue Aug 16 2016 11:16:50 GMT+0300 (MSK)] [info]   Hash for this shard is: 7df5ff8cd1ab7a69b5864ac1305c08c459e6ec7c
 [Tue Aug 16 2016 11:16:50 GMT+0300 (MSK)] [info]   Audit generation for shard done.
 [Tue Aug 16 2016 11:16:50 GMT+0300 (MSK)] [info]   Waiting on a storage offer from the network...
 [Tue Aug 16 2016 11:16:50 GMT+0300 (MSK)] [info]   Adding shard metadata for 7df5ff8cd1ab7a69b5864ac1305c08c459e6ec7c to frame
 [Tue Aug 16 2016 11:16:52 GMT+0300 (MSK)] [info]   Adding shard metadata for 7df5ff8cd1ab7a69b5864ac1305c08c459e6ec7c to frame
 [Tue Aug 16 2016 11:16:54 GMT+0300 (MSK)] [info]   Adding shard metadata for 7df5ff8cd1ab7a69b5864ac1305c08c459e6ec7c to frame
 [Tue Aug 16 2016 11:16:56 GMT+0300 (MSK)] [info]   Adding shard metadata for 7df5ff8cd1ab7a69b5864ac1305c08c459e6ec7c to frame
 [Tue Aug 16 2016 11:16:58 GMT+0300 (MSK)] [info]   Adding shard metadata for 7df5ff8cd1ab7a69b5864ac1305c08c459e6ec7c to frame
 [Tue Aug 16 2016 11:17:01 GMT+0300 (MSK)] [info]   Adding shard metadata for 7df5ff8cd1ab7a69b5864ac1305c08c459e6ec7c to frame
 [Tue Aug 16 2016 11:17:03 GMT+0300 (MSK)] [info]   Adding shard metadata for 7df5ff8cd1ab7a69b5864ac1305c08c459e6ec7c to frame
 [Tue Aug 16 2016 11:17:05 GMT+0300 (MSK)] [warn]   Failed to upload shard...
 [Tue Aug 16 2016 11:17:05 GMT+0300 (MSK)] [warn]   Error occured. Triggering cleanup...
 [Tue Aug 16 2016 11:17:05 GMT+0300 (MSK)] [info]   Cleaning up...
 [Tue Aug 16 2016 11:17:05 GMT+0300 (MSK)] [info]   Finished cleaning!
 [Tue Aug 16 2016 11:17:05 GMT+0300 (MSK)] [error]  Error: Consignment is not authorized
    at Request._callback (/home/osboxes/Documents/gitrepos/core/lib/bridgeclient.js:887:23)
    at Request.self.callback (/home/osboxes/Documents/gitrepos/core/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/osboxes/Documents/gitrepos/core/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/osboxes/Documents/gitrepos/core/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
 [Tue Aug 16 2016 11:17:05 GMT+0300 (MSK)] [error]  Consignment is not authorized
```

### Steps to Reproduce

1. Run Bridge server with number of minions of 2 and concurrency set 2
2. Create login and bucket(or use the existing )
3. Try to upload file into network via Bridge server using Storj CLI, like: node bin/storj.js upload-file 57ab6354a5ce2d240e2632aa ~/test.txt

**Comment by genavyshel** [comment]
Looking through the logs of farmer that initially returns this messages i've mentioned that consigment was rejected due to differing NodeID of contract Issuer  and contract sender(please see the log below)
This happens all the time then bridge sever is runnig 2 minions and degree of concurrency 2


```
[_handleConsignment] RequestParams: {
	"data_hash": "6feec443ea4f1408c625302704c399aeb816899d",
	"audit_tree": ["9986b399e2237dce6453239327bd4131a1ff4668",
	"e474d6e3db4ab686a3b5ce8f243b415834500494",
	"12bdaac8f14c71685e054bf1c592bb5e9e0c6d7f",
	"ba084d3f143f2896809d3f1d7dffed472b39d8de"],
	"contact": {
		"protocol": "0.7.1",
		"address": "95.165.172.5",
		"port": 22388,
		"nodeID": "**1fc7e2055dda4f58850b6046348d2331ca532716**",
		"lastSeen": 1471334259199
	},
	"nonce": 1471335280716,
	"signature": "IJJOLCL0+f3BpxIHEoGWzSHh8E5pjIiyStVCWFns2sBYayB2UXyynaU8/l/jVQ/inTHZhD9flrTe1yXxBTcBDi4="
}

storjshare-0[_handleConsignment]items: {
	"hash": "6feec443ea4f1408c625302704c399aeb816899d",
	"shard": {
		"_writableState": {
			"objectMode": false,
			"highWaterMark": 16384,
			"needDrain": false,
			"ending": false,
			"ended": false,
			"finished": false,
			"decodeStrings": true,
			"defaultEncoding": "utf8",
			"length": 0,
			"writing": false,
			"corked": 0,
			"sync": true,
			"bufferProcessing": false,
			"writecb": null,
			"writelen": 0,
			"bufferedRequest": null,
			"lastBufferedRequest": null,
			"pendingcb": 0,
			"prefinished": false,
			"errorEmitted": false,
			"bufferedRequestCount": 0,
			"corkedRequestsFree": {
				"next": null,
				"entry": null
			}
		},
		"writable": true,
		"domain": null,
		"_events": {
			
		},
		"_eventsCount": 0
	},
	"contracts": {
		**"28b709aa2daf0c72ed5de9261eebcc75ac52646f"**: {
			"audit_count": 3,
			"data_hash": "6feec443ea4f1408c625302704c399aeb816899d",
			"data_size": 203,
			"farmer_id": "0be4827c998901b463884564db8c36d12e84cd76",
			"farmer_signature": "H44WWzOfYFecsemyQIzFT1VrDapzkVejT3KIu+r/xw0LMz+hjby5aTu+pHjRjQc2PhjDebTeLHBbky59YRo7bu0=",
			"payment_destination": "1PBRGeMX9E7mtd5aga3c3JMAwqoiHcXpw4",
			"payment_download_price": 0,
			"payment_storage_price": 0,
			"renter_id": "28b709aa2daf0c72ed5de9261eebcc75ac52646f",
			"renter_signature": "IIQjCbvj0Nspn3D/GJkjtsO+A03k5jJ0L9zdsGM3D5fdPHV4nw7HONNMnKUn1cKAF2sopOmyHn4oREteUBj60ho=",
			"store_begin": 1471335278342,
			"store_end": 1479111278342,
			"version": 0
		}
	},
	"trees": {
		
	},
	"challenges": {
		
	},
	"meta": {
		"28b709aa2daf0c72ed5de9261eebcc75ac52646f": {
			
		}
	},
	"modified": 1471335280178
}
```

**Comment by bookchin** [comment]
Check your config for bridge and make sure that the minions are set you use the same private key.

**Comment by genavyshel** [comment]
It works! thanks.
