### ISSUE TITLE
[error] Error: Shard data not found

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#261]
### Package Versions

Replace the values below using the output from `npm list storj`. Use `npm list -g storj` if installed globally.

```
storj-bridge@1.2.0 /home/gordon/Code/storj-bridge
└── storj@4.1.0  -> /home/gordon/Code/storj-core

ctorj-CLI -> 1.0.16
```

Replace the values below using the output from `node --version`.

```
v4.6.0
```
### Expected Behavior

```
Upload continues
```
### Upload Command

```
set temp=E:\Upload\temp

for /l %%x in (1, 1, 1000) do (
   echo %%x
   storj -k meije0612 -r 12 upload-file 4c1dcb7b5b4b127936142f2d D:\movies\*   
   TIMEOUT 2
)
```
### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
[Tue Oct 25 2016 18:45:11 GMT+0200 (W. Europe Daylight Time)] [info]   2 of 29 files uploaded
 [Tue Oct 25 2016 18:45:11 GMT+0200 (W. Europe Daylight Time)] [warn]   [ call.the.midwife.s05e01.hdtv.x264-tla[ettv].mp4 ] Already exists in bucket. Uploading to (2
016-10-25T16;45;11.497Z)-call.the.midwife.s05e01.hdtv.x264-tla[ettv].mp4
 [Tue Oct 25 2016 18:45:11 GMT+0200 (W. Europe Daylight Time)] [info]   Encrypting file "D:/movies/call.the.midwife.s05e01.hdtv.x264-tla[ettv].mp4"
 [Tue Oct 25 2016 18:45:13 GMT+0200 (W. Europe Daylight Time)] [error]  Error: Shard data not found<br> &nbsp; &nbsp;at Request._callback (/opt/storj/bridge/node_mod
ules/storj-complex/lib/client.js:62:25)<br> &nbsp; &nbsp;at Request.self.callback (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:187:2
2)<br> &nbsp; &nbsp;at emitTwo (events.js:87:13)<br> &nbsp; &nbsp;at Request.emit (events.js:172:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/opt/storj/bridge/
node_modules/storj-complex/node_modules/request/request.js:1048:10)<br> &nbsp; &nbsp;at emitOne (events.js:77:13)<br> &nbsp; &nbsp;at Request.emit (events.js:169:7)<
br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:969:12)<br> &nbsp; &nbsp;at emitN
one (events.js:72:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:913:12)<br> &nbsp; &nbsp;at n
extTickCallbackWith2Args (node.js:442:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:356:17)

 [Tue Oct 25 2016 18:45:41 GMT+0200 (W. Europe Daylight Time)] [info]   [ (2016-10-25T16;45;11.497Z)-call.the.midwife.s05e01.hdtv.x264-tla[ettv].mp4 ] Encryption com
```
### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.
1. Run a upload script of files 1-2GB.
2. Hope the error pops-up.

**Comment by littleskunk** [comment]
Bridge issue because the bridge returned a stacktrace: `Request._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:62:25)`

**Comment by bookchin** [comment]
Belongs in complex
