### ISSUE TITLE
 Error: Key not found in database

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#270]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@4.1.0 /home/gordon/Code/storj-bridge
└── storj@1.2.0  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v6.3.1
```

### Expected Behavior

No errors.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Tue Nov 01 2016 13:49:24 GMT+0100 (W. Europe Standard Time)] [info]   [ (2016-11-01T12;49;24.419Z)-1047.full.pdf ] Creating storage token... (retry: 0)
 [Tue Nov 01 2016 13:49:25 GMT+0100 (W. Europe Standard Time)] [info]   [ (2016-11-01T12;49;24.419Z)-1047.full.pdf ] Storing file, hang tight!
 [Tue Nov 01 2016 13:49:25 GMT+0100 (W. Europe Standard Time)] [info]   Trying to upload shard C:\Users\Meije\AppData\Local\Temp\ddd30c9b3762 index 0
 [Tue Nov 01 2016 13:49:25 GMT+0100 (W. Europe Standard Time)] [info]   Hash for this shard is: fe33f206c8a5231a1b17f29c6cfcfc8c2f8dfd27
 [Tue Nov 01 2016 13:49:25 GMT+0100 (W. Europe Standard Time)] [error]  Error: Key not found in database [8686b60a2c6fab98d4a09e78cfc243ba3740c34c]<br> &nbsp; &nbsp;at Request._callback (/opt/storj/bridge/node_modules/storj-complex/lib/client.js:62:25)<br> &nbsp; &nbsp;at Request.self.callback (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:186:22)<br> &nbsp; &nbsp;at emitTwo (events.js:87:13)<br> &nbsp; &nbsp;at Request.emit (events.js:172:7)<br> &nbsp; &nbsp;at Request.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:1060:10)<br> &nbsp; &nbsp;at emitOne (events.js:77:13)<br> &nbsp; &nbsp;at Request.emit (events.js:169:7)<br> &nbsp; &nbsp;at IncomingMessage.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/storj-complex/node_modules/request/request.js:980:12)<br> &nbsp; &nbsp;at IncomingMessage.g (events.js:260:16)<br> &nbsp; &nbsp;at emitNone (events.js:72:20)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:166:7)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:913:12)<br> &nbsp; &nbsp;at nextTickCallbackWith2Args (node.js:442:9)<br> &nbsp; &nbsp;at process._tickCallback (node.js:356:17)

 [Tue Nov 01 2016 13:49:25 GMT+0100 (W. Europe Standard Time)] [info]   Audit generation for shard done.
 [Tue Nov 01 2016 13:49:25 GMT+0100 (W. Europe Standard Time)] [info]   Waiting on a storage offer from the network...
 [Tue Nov 01 2016 13:49:25 GMT+0100 (W. Europe Standard Time)] [info]   Querying bridge for contract for fe33f206c8a5231a1b17f29c6cfcfc8c2f8dfd27 (retry: 0)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Run a upload script
2. Hope to get the error

**Comment by littleskunk** [comment]
Moved to https://github.com/Storj/complex/issues/18
