### ISSUE TITLE
Early termination of response with listing many files in a bucket

### ISSUE THREAD

**Issue by vevarm** [Storj/bridge#282]
### Package Versions

:~$ storj --version ; storj get-info
Storjcli: 2.0.1 | Core: 5.1.0
 [Mon Nov 14 2016 16:47:33 GMT+0100 (CET)] [info]   Title:             Storj Bridge
 [Mon Nov 14 2016 16:47:33 GMT+0100 (CET)] [info]   Description:       Access the Storj network using a simple REST API.
 [Mon Nov 14 2016 16:47:33 GMT+0100 (CET)] [info]   Version:           2.1.0

### Expected Behavior

Files are listed in bucket

```

### Actual Behavior

.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-cli/bin/actions/files.js:19
files.forEach(function(file) {
^

TypeError: files.forEach is not a function
at /home/-/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-cli/bin/actions/files.js:19:11
at Request._callback (/home/-/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-lib/lib/bridge-client/index.js:1061:5)
at Request.self.callback (/home/-/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/request/request.js:186:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request.<anonymous> (/home/-/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/request/request.js:1081:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage.<anonymous> (/home/-/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/request/request.js:1001:12)
at IncomingMessage.g (events.js:291:16)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:974:12)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)


```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. create a bucket
2. upload small files to it for a week
3. try list all files

**Comment by vevarm** [comment]
i estimate the bucket to have like 50k files, this is based on number of keys the cli client has created.

**Comment by vevarm** [comment]
I also get this for an newly created empty bucket, hmm? That is kind of strange.

**Comment by vevarm** [comment]
Can you please reopen this. This is reproducable 100% of the times with many files in buckets.

**Comment by vevarm** [comment]
x:~$  storj --version ;  storj get-info ; date ; storj list-files x | head ; date
Storjcli: 2.0.1 | Core: 5.1.2
 [Sat Nov 19 2016 17:36:04 GMT+0100 (CET)] [info]   Title:             Storj Bridge
 [Sat Nov 19 2016 17:36:04 GMT+0100 (CET)] [info]   Description:       Access the Storj network using a simple REST API.
 [Sat Nov 19 2016 17:36:04 GMT+0100 (CET)] [info]   Version:           2.2.3
 [Sat Nov 19 2016 17:36:04 GMT+0100 (CET)] [info]   Host:              0.0.0.0
lÃ¶r 19 nov 2016 17:36:04 CET
/home/x/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-cli/bin/actions/files.js:19
    files.forEach(function(file) {
          ^

TypeError: files.forEach is not a function
    at /home/x/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-cli/bin/actions/files.js:19:11
    at Request._callback (/home/x/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/storj-lib/lib/bridge-client/index.js:1079:5)
    at Request.self.callback (/home/x/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/x/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/x/.nvm/versions/node/v6.9.1/lib/node_modules/storj/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
lÃ¶r 19 nov 2016 17:48:17 CET

**Comment by vevarm** [comment]
I have tested directly agains api. This is what happens. The bucket data starts to stream imidiatly. after 13 minutes the stream gets cut (possibly due to open cursor timeout). This allows to download about 4MB of data which in this case is info about ~25K files. This must be a pretty draining api call on the gateway. 

This may not be prio to fix currently but at some point it needs attention, 25K files is not that many and possibly people have worse latency than me, meaining this will result in even fewer fies and also do you really want to keep an upen cursor for this long? It risks exhausting db resources. 




 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4200k    0 4200k    0     0   5501      0 --:--:--  0:13:01 --:--:--  2794
curl: (18) transfer closed with outstanding read data remaining

**Comment by braydonf** [comment]
This looks like issue for core-cli

**Comment by vevarm** [comment]
can reproduced with curl as stated above so not a cli issue its a bridge problen

**Comment by littleskunk** [comment]
```
% Total % Received % Xferd Average Speed Time Time Time Current
 Dload Upload Total Spent Left Speed
 100 4200k 0 4200k 0 0 5501 0 --:--:-- 0:13:01 --:--:-- 2794
 curl: (18) transfer closed with outstanding read data remaining
```

**Comment by braydonf** [comment]
Okay, missed that part. There may be another issue at the CLI, but it looks like there is one here too.
