### ISSUE TITLE
fileName.replace is not a function

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#285]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@2.1.0/home/gordon/Code/storj-bridge
└── storj@5.1.0 -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
I am able to download a file
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
command: storj -d download-file -k meije0612 994ee4759cfc6292f7f5dde3 7fd4845122ccf732d6aba13a D:\downloads

1
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
 [Mon Nov 14 2016 21:13:33 GMT+0100 (W. Europe Standard Time)] [debug]  Parameter for ECDSA signature: GET\n/buckets/994ee4759cfc6292f7f5dde3/files/7fd4845122ccf732d6aba1
a/info\n__nonce=86df4079-bbd1-497e-8735-b09f8d15efd1
 [Mon Nov 14 2016 21:13:33 GMT+0100 (W. Europe Standard Time)] [debug]  Request: {"baseUrl":"https://api.storj.io","uri":"/buckets/994ee4759cfc6292f7f5dde3/files/7fd48451
2ccf732d6aba13a/info","method":"GET","timeout":10000,"qs":{"__nonce":"86df4079-bbd1-497e-8735-b09f8d15efd1"},"json":true,"headers":{"x-pubkey":"03553df194912c83244ad0a378
3bdaecb9e22df1d853b0cb2eef23a4a976ca782","x-signature":"304402202a93444bd0d8ddb4cac04719d99d94b74dd6055f70c1f09a93f34bf38030b2db022028acabd746101c750b1a1df305cd7353cb3432
65efde462a9c51e040be0e750"}}
 [Mon Nov 14 2016 21:13:34 GMT+0100 (W. Europe Standard Time)] [debug]  Body: {"bucket":"994ee4759cfc6292f7f5dde3","mimetype":"video/mp4","filename":{"_id":"5829b3cf80fce
089f874502","user":"meijesibbel@hotmail.com","__v":23,"shards":["5829b3d9e9c0b45346b0fe0b","5829b3e6eb8c4f7b13a49eeb","5829b3e894a2a660dc6a8126","5829b3eceeb71b73ac017279
,"5829b3efdfc58538e7df1963","5829b3fd5946cc6c7757a4a1","5829b3ffe777245d85961232","5829b403730e0006c6a98815","5829b4152268fa6359b34a13","5829b436e246b6552f53dc44","5829b4
142699055d1d37a6f","5829b4752268fa6359b34a1f","5829b495d29da871907ffd26","5829b4b0df415d78f22faca4","5829b4d80cb04b03cca445f5","5829b4e52657f90e888a113b","5829b4ef02e7772
bfadf833","5829b50880fb5d64a26eb344","5829b672eb8c4f7b13a49f4e","5829b9939dc1da72366f5896"],"size":763809061,"locked":true,"created":"2016-11-14T12:53:35.900Z"},"frame":"
829b3cf80fce5089f874502","size":763809061,"id":"7fd4845122ccf732d6aba13a"}
 [Mon Nov 14 2016 21:13:34 GMT+0100 (W. Europe Standard Time)] [info]   Name: [object Object], Type: video/mp4, Size: 763809061 bytes, ID: 7fd4845122ccf732d6aba13a
C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\downloader.js:74
  return fileName.replace(re, '');
                  ^

TypeError: fileName.replace is not a function
    at Downloader._stripISOString (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\downloader.js:74:19)
    at C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-cli\bin\actions\downloader.js:94:35
    at Request._callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client\index.js:1061:5)
    at Request.self.callback (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Waiting for 0 seconds, press a key to continue ...
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Try to download a file
2. ...
3. ...

**Comment by MeijeSibbel** [comment]
Related to: https://github.com/Storj/bridge/issues/283

**Comment by bookchin** [comment]
https://github.com/Storj/service-storage-models/releases/tag/v5.0.3

**Comment by MeijeSibbel** [comment]
@bookchin ,When will this be implemented into the bridge?

**Comment by bookchin** [comment]
Soon:tm:
