### ISSUE TITLE
File download MongoError

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#311]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
Storjcli: 4.0.0 | Core: 6.0.10
```

Replace the values below using the output from `node --version`.

```
v6.9.2
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
File Download without any problems.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
[Mon Dec 19 2016 08:49:04 GMT+0000 (UTC)] [warn]   Request failed, reason: MongoError: connection 1804 to 104.196.1.20:27020 timed out<br> &nbsp; &nbsp;at Function.MongoError.create (/opt/storj/bridge/node_modules/mongodb-core/lib/error
.js:29:11)<br> &nbsp; &nbsp;at TLSSocket.&lt;anonymous&gt; (/opt/storj/bridge/node_modules/mongodb-core/lib/connection/connection.js:186:20)<br> &nbsp; &nbsp;at TLSSocket.g (events.js:291:16)<br> &nbsp; &nbsp;at emitNone (events.js:86:13
)<br> &nbsp; &nbsp;at TLSSocket.emit (events.js:185:7)<br> &nbsp; &nbsp;at TLSSocket.Socket._onTimeout (net.js:339:8)<br> &nbsp; &nbsp;at ontimeout (timers.js:365:14)<br> &nbsp; &nbsp;at tryOnTimeout (timers.js:237:5)<br> &nbsp; &nbsp;at
 Timer.listOnTimeout (timers.js:207:5)
```

**Comment by braydonf** [comment]
We're monitoring the health of the database connection and it has been stable.
