### ISSUE TITLE
Bridge errors during network stress-testing 

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#440]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@5.14.1 /home/gordon/Code/storj-bridge
└── latest core-CLI
```

Replace the values below using the output from `node --version`.

```
v6.10.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
No errors 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Mon May 08 2017 01:19:26 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:19:32 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>RangeError: Invalid status code: 83<br> &nbsp; &nbsp;at ServerResponse.writeHead (_http_server.js:192:11)<br> &nbsp; &nbsp;at ServerResponse._implicitHeader (_http
rver.js:157:8)<br> &nbsp; &nbsp;at ServerResponse.OutgoingMessage.end (_http_outgoing.js:574:10)<br> &nbsp; &nbsp;at ServerResponse.send (/storj/bridge/node_modules/exp
s/lib/response.js:211:10)<br> &nbsp; &nbsp;at ServerResponse.json (/storj/bridge/node_modules/express/lib/response.js:256:15)<br> &nbsp; &nbsp;at ServerResponse.send (/
rj/bridge/node_modules/express/lib/response.js:158:21)<br> &nbsp; &nbsp;at errorhandler (/storj/bridge/node_modules/storj-service-middleware/lib/error-handler.js:17:37)
> &nbsp; &nbsp;at Layer.handle_error (/storj/bridge/node_modules/express/lib/router/layer.js:71:5)<br> &nbsp; &nbsp;at trim_prefix (/storj/bridge/node_modules/express/l
router/index.js:315:13)<br> &nbsp; &nbsp;at /storj/bridge/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/storj/bridge/node
dules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/storj/bridge/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at next (/storj/brid
node_modules/express/lib/router/route.js:127:14)<br> &nbsp; &nbsp;at Layer.handle_error (/storj/bridge/node_modules/express/lib/router/layer.js:67:12)<br> &nbsp; &nbsp;
next (/storj/bridge/node_modules/express/lib/router/route.js:135:13)<br> &nbsp; &nbsp;at /storj/bridge/node_modules/storj-service-middleware/lib/authenticate.js:115:16<
 &nbsp; &nbsp;at /storj/bridge/node_modules/mongoose/lib/model.js:3737:16<br> &nbsp; &nbsp;at /storj/bridge/node_modules/mongoose/lib/services/model/applyHooks.js:151:1
r> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:73:7)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:104:9)</pre>
</body>
</html>
 - retrying(false)...
 [Mon May 08 2017 01:19:32 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for 4ed3c3f7c8aaa7b2511c30b60b0e4c797cc3a596 (retry: 9)
 [Mon May 08 2017 01:19:35 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:19:35 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:19:35 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:19:36 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

**Comment by MeijeSibbel** [comment]
```
 [Mon May 08 2017 01:50:07 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:07 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for dfb4ad7e97a07f48bf59dceb66b8d5a284d44e3b (retry: 3)
 [Mon May 08 2017 01:50:08 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:09 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:09 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:09 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>RangeError: Invalid status code: 50<br> &nbsp; &nbsp;at ServerResponse.writeHead (_http_server.js:192:11)<br> &nbsp; &nbsp;at ServerResponse._implicitHeader (_http_s
rver.js:157:8)<br> &nbsp; &nbsp;at ServerResponse.OutgoingMessage.end (_http_outgoing.js:574:10)<br> &nbsp; &nbsp;at ServerResponse.send (/storj/bridge/node_modules/expre
s/lib/response.js:211:10)<br> &nbsp; &nbsp;at ServerResponse.json (/storj/bridge/node_modules/express/lib/response.js:256:15)<br> &nbsp; &nbsp;at ServerResponse.send (/st
rj/bridge/node_modules/express/lib/response.js:158:21)<br> &nbsp; &nbsp;at errorhandler (/storj/bridge/node_modules/storj-service-middleware/lib/error-handler.js:17:37)<b
> &nbsp; &nbsp;at Layer.handle_error (/storj/bridge/node_modules/express/lib/router/layer.js:71:5)<br> &nbsp; &nbsp;at trim_prefix (/storj/bridge/node_modules/express/lib
router/index.js:315:13)<br> &nbsp; &nbsp;at /storj/bridge/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/storj/bridge/node_m
dules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/storj/bridge/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at next (/storj/bridge
node_modules/express/lib/router/route.js:127:14)<br> &nbsp; &nbsp;at Layer.handle_error (/storj/bridge/node_modules/express/lib/router/layer.js:67:12)<br> &nbsp; &nbsp;at
next (/storj/bridge/node_modules/express/lib/router/route.js:135:13)<br> &nbsp; &nbsp;at /storj/bridge/node_modules/storj-service-middleware/lib/authenticate.js:87:16<br>
&nbsp; &nbsp;at /storj/bridge/node_modules/mongoose/lib/model.js:3737:16<br> &nbsp; &nbsp;at /storj/bridge/node_modules/kareem/index.js:220:48<br> &nbsp; &nbsp;at /storj/
ridge/node_modules/kareem/index.js:131:16<br> &nbsp; &nbsp;at _combinedTickCallback (internal/process/next_tick.js:73:7)<br> &nbsp; &nbsp;at process._tickCallback (intern
l/process/next_tick.js:104:9)</pre>
</body>
</html>
 - retrying(false)...
 [Mon May 08 2017 01:50:09 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for b1a4c1678252da57604c102be7dc433ae79be11f (retry: 4)
 [Mon May 08 2017 01:50:09 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:14 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:15 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:15 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:18 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:18 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:19 GMT+0200 (W. Europe Daylight Time)] [warn]   Request failed, reason: ESOCKETTIMEDOUT - retrying(true)...
 [Mon May 08 2017 01:50:19 GMT+0200 (W. Europe Daylight Time)] [info]   Querying bridge for contract for cdab64cb7ae1ef8789cfacae36c54db317f20b07 (retry: 4)
```

**Comment by braydonf** [comment]
Part of timeouts for storage offers as listed in: https://github.com/Storj/bridge/issues/398
