### ISSUE TITLE
Cannot set property 'isEstablished' of undefined

### ISSUE THREAD

**Issue by Th3Van** [Storj/bridge#465]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
title	"Storj Bridge"
version	"5.21.2"
x-protocol-version "1.1.0-Th3van-Test"
x-core-version	"6.5.0"
```

Replace the values below using the output from `node --version`.

```
v6.10.3
```
### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

My test bridge (http://api.test.storj.dk) has been "running" for like 24 hours, but it did shutdown like 10 times randomly, and exits with the same error every time :
```
{"level":"info","message":"received exchange report","timestamp":"2017-06-12T19:13:57.102Z"}
{"level":"info","message":"exchange report saved","timestamp":"2017-06-12T19:13:57.103Z"}
{"level":"info","message":"received exchange report","timestamp":"2017-06-12T19:13:57.273Z"}
{"level":"info","message":"exchange report saved","timestamp":"2017-06-12T19:13:57.277Z"}
{"level":"warn","message":"Auto mirroring limit is reached","timestamp":"2017-06-12T19:13:57.280Z"}
{"level":"error","message":"an unhandled exception occurred: TypeError: Cannot set property 'isEstablished' of undefined
    at /root/bridge/lib/server/routes/frames.js:262:34
    at /root/bridge/node_modules/storj-lib/lib/storage/manager.js:64:5
    at /root/bridge/node_modules/storj-lib/lib/storage/adapter.js:64:5
    at /root/bridge/node_modules/storj-mongodb-adapter/lib/adapter.js:48:5
    at Query.<anonymous> (/root/bridge/node_modules/mongoose/lib/model.js:3748:16)
    at /root/bridge/node_modules/kareem/index.js:277:21
    at /root/bridge/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)","timestamp":"2017-06-12T19:13:57.581Z"}
{"level":"info","message":"bridge service is shutting down","timestamp":"2017-06-12T19:13:57.581Z"}
```
My test bridge are using default settings, except for these : 

**/root/bridge/lib/constants.js :**

```
DEFAULT_FILE_TTL: '1d',
M_REPLICATE: 0,
```
**/root/.storj-bridge/config/develop :**
```
{
  "storage": {
    "mongoUrl": "mongodb://127.0.0.1:27017/storj-complex",
    "mongoOpts": {}
  },
  "server": {
    "host": "109.232.77.16",
    "port": 80,
    "timeout": 240000,
    "ssl": {
      "cert": null,
      "key": null,
      "ca": [],
      "redirect": 80
    },
    "public": {
      "host": "109.232.77.16",     
      "port": 80
    }
  },
  "complex": {
    "rpcUrl": "http://127.0.0.1:8080",
    "rpcUser": "****",
    "rpcPassword": "****"
  },
  "logger": {
    "level": 4
  },
  "mailer": {
    "host": "*******",
    "port": 25,
    "secure": false,
    "auth": {
      "user": "*******",
      "pass": "**********"
    },
    "from": "**********"
  },
  "application": {
    "shardsPerMinute": 10000,
    "farmerTimeoutIgnore": "10m",
    "freeTier": {
      "up": {
        "hourlyBytes": 3000000000,
        "dailyBytes": 10000000000,
        "monthlyBytes": 60000000000
      },
      "down": {
        "hourlyBytes": 9000000000,
        "dailyBytes": 30000000000,
        "monthlyBytes": 180000000000
      }
    }
  },
  "redis": {
    "host": "localhost",
    "port": 6379
  }
}
```
**complex-landlord.json :**
```
root@bridge1110:~# cat complex-landlord.json
[
  {
    "type": "Landlord",
    "opts": {
      "mongoUrl": "mongodb://127.0.0.1:27017/storj-complex",
      "mongoOpts": {},
      "logLevel": 0,
      "amqpUrl": "amqp://127.0.0.1",
      "amqpOpts": {},
      "serverPort": 8080,
      "serverOpts": {
        "certficate": null,
        "key": null,
        "authorization": {
          "username": "****",
          "password": "****"
        }
      }
    }
  }
]
```
**complex-renter01.json :**
```
root@bridge1110:~# cat complex-renter01.json
[
  {
    "type": "Renter",
    "opts": {
      "logLevel": 0,
      "amqpUrl": "amqp://127.0.0.1",
      "amqpOpts": {},
      "mongoUrl": "mongodb://127.0.0.1:27017/storj-complex",
      "mongoOpts": {},
      "networkPrivateExtendedKey": "/root/complex/example/network-private-key",
      "networkIndex": 16001,
      "networkOpts": {
        "rpcPort": 4001,
        "rpcAddress": "109.232.77.16",
        "doNotTraverseNat": true,
        "tunnelServerPort": 5002,
        "tunnelGatewayRange": {
          "min": 6010,
          "max": 6014
        },
        "maxTunnels": 0,
        "seedList": [],
        "bridgeUri": null,
        "maxConnections": 5000
      }
    }
  }
]
```

### 3. part software :
**storj-complex :**
```
root@bridge1110:~/bridge# storj-complex --version
5.5.0
```
**MongoDB :**
```
root@bridge1110:~/bridge# mongo --version
MongoDB shell version v3.4.4
git version: 888390515874a9debd1b6c5d36559ca86b44babd
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: debian81
    distarch: x86_64
    target_arch: x86_64
```
**RabbitMQ-Server :**
```
root@bridge1110:~/bridge# rabbitmqctl status
Status of node rabbit@bridge1110
[{pid,31779},
 {running_applications,
     [{rabbit,"RabbitMQ","3.6.10"},
      {rabbit_common,
          "Modules shared by rabbitmq-server and rabbitmq-erlang-client",
          "3.6.10"},
      {os_mon,"CPO  CXC 138 46","2.4.1"},
      {ranch,"Socket acceptor pool for TCP protocols.","1.3.0"},
      {ssl,"Erlang/OTP SSL application","8.1"},
      {public_key,"Public key infrastructure","1.3"},
      {crypto,"CRYPTO","3.7.2"},
      {compiler,"ERTS  CXC 138 10","7.0.3"},
      {asn1,"The Erlang ASN1 compiler version 4.0.4","4.0.4"},
      {syntax_tools,"Syntax tools","2.1.1"},
      {xmerl,"XML parser","1.3.12"},
      {mnesia,"MNESIA  CXC 138 12","4.14.2"},
      {sasl,"SASL  CXC 138 11","3.0.2"},
      {stdlib,"ERTS  CXC 138 10","3.2"},
      {kernel,"ERTS  CXC 138 10","5.1.1"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:12:12] [async-threads:192] [kernel-poll:true]\n"},
 {memory,
     [{total,172841016},
      {connection_readers,3436512},
      {connection_writers,4396008},
      {connection_channels,16481224},
      {connection_other,42611728},
      {queue_procs,6180224},
      {queue_slave_procs,0},
      {plugins,0},
      {other_proc,24974984},
      {mnesia,528000},
      {metrics,2422968},
      {mgmt_db,0},
      {msg_index,247856},
      {other_ets,5942016},
      {binary,29228016},
      {code,21271684},
      {atom,891849},
      {other_system,16648179}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,55880880947},
 {disk_free_limit,50000000},
 {disk_free,145951080448},
 {file_descriptors,
     [{total_limit,924},
      {total_used,13},
      {sockets_limit,829},
      {sockets_used,11}]},
 {processes,[{limit,1048576},{used,12099}]},
 {run_queue,0},
 {uptime,347977},
 {kernel,{net_ticktime,60}}]
```
**Redis :**
```
root@bridge1110:~/bridge# redis-server --version
Redis server v=3.2.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=afe306bb74b5b69a
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. start storj-bridge
2. add some nodes (storjshare)
3. upload random data for hours.

**Comment by braydonf** [comment]
Closed in https://github.com/Storj/bridge/pull/466
