### ISSUE TITLE
contract-renew.integration.js test throws an exception

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#560]
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
v7.4.1
```

Replace the values below using the output from `node --version`.

```
v8.9.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

All tests passed.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Last travis build and the current tests on my local machine are failing. https://travis-ci.org/Storj/bridge/builds/329112045

I added a console.log to get the full error output.
```
> storj-bridge@7.4.1 integration /root/bridge
> NODE_ENV=test _mocha --recursive test-integration/**



  ContractRenewalJob
{ Error: Command failed: node /root/bridge/bin/storj-contract-renew.js --config /root/bridge/test-integration/_fixtures/contract-renew-test-config.json --datadir /root/bridge/test-integration/_fixtures
/root/bridge/node_modules/storj-complex/lib/client.js:83
      args[1] = storj.Contract(args[1]);
                                   ^

TypeError: Cannot read property '1' of undefined
    at Client._deserializeResponseArguments (/root/bridge/node_modules/storj-complex/lib/client.js:83:36)
    at Request._callback (/root/bridge/node_modules/storj-complex/lib/client.js:68:12)
    at Request.self.callback (/root/bridge/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/bridge/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/bridge/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node /root/bridge/bin/storj-contract-renew.js --config /root/bridge/test-integration/_fixtures/contract-renew-test-config.json --datadir /root/bridge/test-integration/_fixtures' }
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. `git clone https://github.com/Storj/bridge && cd bridge`
2. `npm install`
3. `npm test`

**Comment by nat-ventura** [comment]
Just for further documentation, here is the place where the problem line comes from:
https://github.com/Storj/complex/blob/master/lib/client.js#L83

**Comment by braydonf** [comment]
This looks currently broken on the master branch. However getting a different error message: 
```
Uncaught SyntaxError: Unexpected end of JSON input
```

**Comment by littleskunk** [comment]
Correct. I added a console.log to get the message that can't be parsed as JSON. See error message above.

**Comment by braydonf** [comment]
Fixed in https://github.com/Storj/bridge/pull/568
