### ISSUE TITLE
Invalid _id when querying for Bucket

### ISSUE THREAD

**Issue by phutchins** [Storj/bridge#77]
I noticed a stack trace in the production API logs that is unable to find a Bucket by _id using req.params.id. It seems that req.params.id is not an ObjectId. It may should be cast to objectId, searched for using id instead of _id, or possibly should be searching some field other than _id.

```
{"level":"error","message":"request error: Cast to ObjectId failed for value \"[info]\" at path \"_id\"","timestamp":"2016-05-26T11:46:27.439Z"}
{"level":"error","message":"CastError: Cast to ObjectId failed for value \"[info]\" at path \"_id\"\n    at MongooseError.CastError (/opt/storj/bridge/node_modules/mongoose/lib/error/cast.js:19:11)\n    at ObjectId.cast (/opt/storj/bridge/node_modules/mongoose/lib/schema/objectid.js:147:13)\n    at ObjectId.castForQuery (/opt/storj/bridge/node_modules/mongoose/lib/schema/objectid.js:187:15)\n    at cast (/opt/storj/bridge/node_modules/mongoose/lib/cast.js:174:32)\n    at Query.cast (/opt/storj/bridge/node_modules/mongoose/lib/query.js:2580:10)\n    at Query.findOne (/opt/storj/bridge/node_modules/mongoose/lib/query.js:1240:10)\n    at Function.findOne (/opt/storj/bridge/node_modules/mongoose/lib/model.js:1272:13)\n    at Query.<anonymous> (/opt/storj/bridge/lib/server/routes/buckets.js:499:16)\n    at /opt/storj/bridge/node_modules/mongoose/node_modules/kareem/index.js:177:19\n    at /opt/storj/bridge/node_modules/mongoose/node_modules/kareem/index.js:109:16\n    at nextTickCallbackWith0Args (node.js:420:9)\n    at process._tickCallback (node.js:349:13)","timestamp":"2016-05-26T11:46:27.440Z"}
```

bridge/ilb/server/routes/buckets.js:499 appears to be where this is happening.

It would be helpful to add some debug logging around this process to get a better idea of what is/should be going on.

**Comment by gordonwritescode** [comment]
This is expected behavior and it is being casted to an object id. If the user requests a bucket by an invalid id, this will happen. The stack trace is printed for debugging purposes but does indicate a crash or restart. 

Example: GET /buckets/invalidobjectid
