### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by galets** [Storj/bridge#90]
```
$ storjcli uploadfile ******************* /tmp/cat.jpg
 [...]  > Enter your passphrase to unlock your keyring  >  ***********************

 [info]   Generating encryption key...
 [info]   Encrypting file "/tmp/cat.jpg"
 [info]   Encryption complete!
 [info]   Creating storage token...
 [info]   Storing file, hang tight!
/usr/lib/node_modules/storj-bridge-client/node_modules/storj/lib/filedemuxer.js:108
  this._currentOutput.push(bytes);
                     ^

TypeError: Cannot read property 'push' of undefined
    at FileDemuxer._pushBytesToOutput (/usr/lib/node_modules/storj-bridge-client/node_modules/storj/lib/filedemuxer.js:108:22)
    at FileDemuxer._closeCurrentOutput (/usr/lib/node_modules/storj-bridge-client/node_modules/storj/lib/filedemuxer.js:116:8)
    at FileDemuxer._handleSourceEnded (/usr/lib/node_modules/storj-bridge-client/node_modules/storj/lib/filedemuxer.js:95:8)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

happens after 

`npm install -g storj-bridge-client`

today (e.g.: 2016-06-09). Arch linux. npm version:

```
npm -v
3.9.2
```

**Comment by bookchin** [comment]
This shouldn't ever happen, but the `storj-bridge-client` package is deprecated. Use https://github.com/Storj/core instead. If you still have the issue after updating to that, open an issue in that repository please.
