### ISSUE TITLE
Renter minion dies and is unable to restart due to port in use

### ISSUE THREAD

**Issue by phutchins** [Storj/bridge#91]
It is likely that we simply need to retry until the port is released.

```
{"level":"warn","message":"rpc call 8ad593695c159aeb15055a4987760d77d7610fac timed out","timestamp":"2016-06-11T01:40:34.399Z"}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8512
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at TunnelGateway.open (/opt/storj/bridge/node_modules/storj/lib/tunnel/gateway.js:166:16)
    at TunnelServer.createGateway (/opt/storj/bridge/node_modules/storj/lib/tunnel/server.js:115:11)
    at Protocol._handleOpenTunnel (/opt/storj/bridge/node_modules/storj/lib/network/protocol.js:362:39)
    at Transport.protocol (/opt/storj/bridge/node_modules/storj/node_modules/kad/lib/hooks/protocol.js:33:12)
    at /opt/storj/bridge/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:607:21
    at /opt/storj/bridge/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:246:17
    at iterate (/opt/storj/bridge/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:146:13)
    at /opt/storj/bridge/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:157:25
    at /opt/storj/bridge/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:248:21
    at /opt/storj/bridge/node_modules/storj/node_modules/kad/node_modules/async/lib/async.js:612:34
    at RenterInterface.Network._checkRateLimiter (/opt/storj/bridge/node_modules/storj/lib/network/index.js:285:12)
{"level":"error","message":"renter minion 593844dc7f0076a1aeda9a6b9788af17e67c1052 exited","timestamp":"2016-06-11T01:40:35.138Z"}
{"level":"error","message":"request error: File not found","timestamp":"2016-06-11T01:41:04.305Z"}
{"level":"error","message":"undefined","timestamp":"2016-06-11T01:41:04.305Z"}
{"level":"error","message":"renter minion 593844dc7f0076a1aeda9a6b9788af17e67c1052 encountered an error: channel closed","timestamp":"2016-06-11T01:41:06.427Z"}
```

**Comment by bookchin** [comment]
Yeah we need better restarts, but also need to find out what's crashing the minion in the first place.

**Comment by littleskunk** [comment]
Workaround (only possible for CLI):
https://storj.readme.io/docs/storjshare-troubleshooting-guide#manual-seed-configuration-with-cli

**Comment by bookchin** [comment]
What's actually happening is the renter minion is *dying* because it's trying to open a tunnel gateway on a port that's already open, then is unable to restart due to a bug in the `RenterPool`.

The bug has been fixed. Will look into core to see why the Renter minion would try to open a gateway that's already in use.

**Comment by littleskunk** [comment]
@phutchins is the renter minion bugfix deployed?
